### ISSUE TITLE
Breaking with readable-stream 2.2.7 and simple-peer

### ISSUE THREAD

**Issue by Right2Drive** [Right2Drive/ease-web#54]
Add post-install step to force `readable-stream` to `v2.0.05` for the time being until resolved by [nodejs/readable-stream/#277](https://github.com/nodejs/readable-stream/issues/277)

**Comment by mcollina** [comment]
Could you verify it's fixed in v2.2.9?

**Comment by Right2Drive** [comment]
Hi @mcollina 

It looks like 2.2.9 did indeed fix the problem! Thank you for the fast repair! Just to give some more information, I know the issue mentioned webpack v1, but this project is using webpack v2. Thanks again!!
